### ISSUE TITLE
No file on nextcloud web interface afer running the script

### ISSUE THREAD

**Issue by GregBluzat** [mrAceT/nextcloud-S3-local-S3-migration#3]
Hello ! 

First of all, thank you for your work on the script.

I have run the migration script to S3 through the steps described, but I have the following problem: No files appear in the nextcloud interface.
- The files are well on the S3
- The files have the right storage ID in oc_filecache, which refers to the right id of "oc_storages".
- Also, if I create a folder from Nextcloud, at the root, it appears in oc_filecache, and the name is prefixed with "file/". So if i create i folder named "MyFolder", it's appears as "file/MyFolder" in oc_filecache. I noticed that for migrated files, there is no prefix, it's just "MyFolder".  
  - Is that a problem? 

I don't really know what else to check, do you have any idea? 

Thanks 

Greg

**Comment by mrAceT** [comment]
Hi @GregBluzat, sorry I missed your question.

You have closed it, you figured it out?

**Comment by maretodoric** [comment]
I have the same issue and would like to figure it out. It would be great if Greg could share the solution.
I cannot see the files from nextcloud web interface but can see them just fine in Android app.

**Comment by mrAceT** [comment]
@maretodoric .. OK, do I understand correctly, that this problem gets fixed upon updating NextCloud.

PS: I / this script naturally assumes you start out with a "healthy Nextcloud instance" ;)

**Comment by maretodoric** [comment]
Not nextcloud (in this case at least) but one of the nextcloud apps that was needed to be updated.
![image](https://github.com/mrAceT/nextcloud-S3-local-S3-migration/assets/42638763/e84184aa-48c3-474c-a115-9f496b68cc9b)
:)
