### ISSUE TITLE
encryption for source versus target stores

### ISSUE THREAD

**Issue by brainchild0** [mrAceT/nextcloud-S3-local-S3-migration#6]
For migration (local to S3), are local encryption settings duplicated for the remote storage, or are they reset?

For example, is the case supported to migrate a local store that is encrypted into an S3 store that is plaintext?

**Comment by mrAceT** [comment]
I do not know, I don't use encryption (mostly because I seen trouble with it..), I would suggest you try it. If you don;t have a big setup and have the SQL backup you can switch back quite easily. If you do have a big setup, I'dd suggest you create a same one with the same settings to test..

**Comment by brainchild0** [comment]
I have reviewed the flow more closely, and it appears that no decryption is being performed, as would be done when the Nextcloud server reads files through its storage system. Rather, the script simply reads files directly from the file system.

As such, the files will be stored as encrypted in the remote target S3 bucket if previously represented as encrypted in the local file system.

I have no idea whether the locally stored key will be used properly to decode the files once they are transferred to the S3 bucket.

**Comment by mrAceT** [comment]
You are correct, the data is "simply" copied. Best thing would be to create a small test-setup and try?

**Comment by mrAceT** [comment]
@brainchild0 Can you confirm (or not) that this migration script works with encrypted files?

**Comment by brainchild0** [comment]
> Can you confirm (or not) that this migration script works with encrypted files?

I have only confirmed achieving the end objectives on such a target by removing decryption as a separate step preceding my invocation of the migration script.

**Comment by mrAceT** [comment]
Thank you for responding, I'll close this isssue then.
